package cpaintus.models.observable;

public enum ObservableList {
	POINTER,
	BOUNDING_BOX,
	PAINT_MODEL,
	SHAPES_LOADED,
	SHAPE_ADDED,
	EDIT_SHAPE,
	DRAW_SETTINGS,
	MENU_ERASE,
	LOAD_IMAGE, 
	UNSELECT_SHAPE, 
	GROUP_SHAPES, 
	UNGROUP_SHAPES, 
	SHAPE_REMOVED,
	CHANGEDCOMMAND,
}
